<script setup lang="ts">
const title = "Basic"
useHead({
    title
})
</script>

<template>
    <span class="flex flex-col gap-2">
        <section>
            <h1>{{ title }}</h1>
            <p>
                This is a basic boilerplate generated by the noonjs <span class="tag">CLI</span> after running
            </p>
            <span class="flex">
                <command text="npm create noon@latest" />
            </span>

            <my-shiki lang="js" code='import Noonjs from "noonjs"
import config from "../config.json"

const noonjs = new Noonjs(config)

noonjs.on("error", error => {
    console.log(error)
})

noonjs.on("started", port => {
    console.log(`✅ Server is running on http://localhost:${port}`)
})

noonjs.start()' />
            <p>
                It loads the configuration from a JSON file, initializes the noonjs server, and sets up listeners to
                handle errors and log the server start message to the console. This is the default starting point for
                noonjs-based backend projects.
            </p>
        </section>

    </span>
</template>
